/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g
 *     -                            On : 2013-04-20 09:11:20
 *     -                for the parser : SCsCParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SCsCParser.h"



/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSCsCParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSCsCParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSCsCParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSCsCParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   SCsCParserTokenNames[23+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ALIASNONAME",
        (pANTLR3_UINT8) "ATTRSEP",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "CONNECTORS",
        (pANTLR3_UINT8) "CONTENT",
        (pANTLR3_UINT8) "ELEMTYPE",
        (pANTLR3_UINT8) "KEYWORD",
        (pANTLR3_UINT8) "LPAR",
        (pANTLR3_UINT8) "LPAR_INT",
        (pANTLR3_UINT8) "LPAR_OSET",
        (pANTLR3_UINT8) "LPAR_SET",
        (pANTLR3_UINT8) "LPAR_TRF",
        (pANTLR3_UINT8) "NAME",
        (pANTLR3_UINT8) "OBJSEP",
        (pANTLR3_UINT8) "RPAR",
        (pANTLR3_UINT8) "RPAR_INT",
        (pANTLR3_UINT8) "RPAR_OSET",
        (pANTLR3_UINT8) "RPAR_SET",
        (pANTLR3_UINT8) "RPAR_TRF",
        (pANTLR3_UINT8) "SENTSEP",
        (pANTLR3_UINT8) "TRIPLESEP",
        (pANTLR3_UINT8) "URL",
        (pANTLR3_UINT8) "WS"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	syntax    (pSCsCParser ctx);
static 
 void
	sentence_sentsep    (pSCsCParser ctx);
static 
 void
	sentence    (pSCsCParser ctx);
static 
 void
	sentence_lv23456    (pSCsCParser ctx);
static 
 void
	sentence_lv1    (pSCsCParser ctx);
static 
 void
	attrsList    (pSCsCParser ctx);
static 
 void
	simpleIdtf_attrsep    (pSCsCParser ctx);
static 
 void
	objectList    (pSCsCParser ctx);
static 
 void
	objsep_IdtfWithInt    (pSCsCParser ctx);
static 
 void
	intSentence    (pSCsCParser ctx);
static 
 void
	intSentenceList    (pSCsCParser ctx);
static 
 void
	intSentence_sentsep    (pSCsCParser ctx);
static 
 void
	internal    (pSCsCParser ctx);
static 
 void
	triple    (pSCsCParser ctx);
static 
 void
	alias    (pSCsCParser ctx);
static 
 void
	setIdtf    (pSCsCParser ctx);
static 
 void
	objsep_AttrsList_idtfWithInt    (pSCsCParser ctx);
static 
 void
	osetIdtf    (pSCsCParser ctx);
static 
 void
	anyIdtf    (pSCsCParser ctx);
static 
 void
	idtf    (pSCsCParser ctx);
static 
 void
	simpleIdtf    (pSCsCParser ctx);
static 
 void
	idtfWithInt    (pSCsCParser ctx);
static void	SCsCParserFree(pSCsCParser ctx);
static void     SCsCParserReset (pSCsCParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new SCsCParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSCsCParser
SCsCParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return SCsCParserNewSSD(instream, NULL);
}

/** \brief Create a new SCsCParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSCsCParser
SCsCParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSCsCParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pSCsCParser) ANTLR3_CALLOC(1, sizeof(SCsCParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in SCsCParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our SCsCParser interface
     */
    ctx->syntax	= syntax;
    ctx->sentence_sentsep	= sentence_sentsep;
    ctx->sentence	= sentence;
    ctx->sentence_lv23456	= sentence_lv23456;
    ctx->sentence_lv1	= sentence_lv1;
    ctx->attrsList	= attrsList;
    ctx->simpleIdtf_attrsep	= simpleIdtf_attrsep;
    ctx->objectList	= objectList;
    ctx->objsep_IdtfWithInt	= objsep_IdtfWithInt;
    ctx->intSentence	= intSentence;
    ctx->intSentenceList	= intSentenceList;
    ctx->intSentence_sentsep	= intSentence_sentsep;
    ctx->internal	= internal;
    ctx->triple	= triple;
    ctx->alias	= alias;
    ctx->setIdtf	= setIdtf;
    ctx->objsep_AttrsList_idtfWithInt	= objsep_AttrsList_idtfWithInt;
    ctx->osetIdtf	= osetIdtf;
    ctx->anyIdtf	= anyIdtf;
    ctx->idtf	= idtf;
    ctx->simpleIdtf	= simpleIdtf;
    ctx->idtfWithInt	= idtfWithInt;
    ctx->free			= SCsCParserFree;
    ctx->reset			= SCsCParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */


      RECOGNIZER->displayRecognitionError = ParserExceptionHandler;
      RECOGNIZER->recover = ParserExceptionRecover;

    /* Install the token table
     */
    PSRSTATE->tokenNames   = SCsCParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
SCsCParserReset (pSCsCParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 SCsCParserFree(pSCsCParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return SCsCParserTokenNames;
}


    void ParserRecover(pANTLR3_BASE_RECOGNIZER recognizer)
    {

      pANTLR3_PARSER      parser;
      pANTLR3_INT_STREAM      is;
      ANTLR3_UINT32 tokType;

      if(!ParserNeedReturn())
        return;

      parser  = (pANTLR3_PARSER) (recognizer->super);
      is    = parser->tstream->istream;

      recognizer->state->errorRecovery  = ANTLR3_FALSE; 
      recognizer->state->failed     = ANTLR3_FALSE;

      tokType = is->_LA(is,1);
      while (tokType!=EOF)
      {
        is->consume(is);
         if(tokType == SENTSEP || tokType == KEYWORD)
          break;
        tokType = is->_LA(is,1);
      }
      
      SetParserNeedRecover(ANTLR3_FALSE);
      
    }


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_sentsep_in_syntax118  */
static	ANTLR3_BITWORD FOLLOW_sentence_sentsep_in_syntax118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016D10) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_sentsep_in_syntax118	= { FOLLOW_sentence_sentsep_in_syntax118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_KEYWORD_in_syntax170  */
static	ANTLR3_BITWORD FOLLOW_KEYWORD_in_syntax170_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016D10) };
static  ANTLR3_BITSET_LIST FOLLOW_KEYWORD_in_syntax170	= { FOLLOW_KEYWORD_in_syntax170_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_syntax203  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_syntax203_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_syntax203	= { FOLLOW_EOF_in_syntax203_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_in_sentence_sentsep247  */
static	ANTLR3_BITWORD FOLLOW_sentence_in_sentence_sentsep247_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_in_sentence_sentsep247	= { FOLLOW_sentence_in_sentence_sentsep247_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SENTSEP_in_sentence_sentsep262  */
static	ANTLR3_BITWORD FOLLOW_SENTSEP_in_sentence_sentsep262_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SENTSEP_in_sentence_sentsep262	= { FOLLOW_SENTSEP_in_sentence_sentsep262_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_lv1_in_sentence311  */
static	ANTLR3_BITWORD FOLLOW_sentence_lv1_in_sentence311_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_lv1_in_sentence311	= { FOLLOW_sentence_lv1_in_sentence311_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_lv23456_in_sentence337  */
static	ANTLR3_BITWORD FOLLOW_sentence_lv23456_in_sentence337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_lv23456_in_sentence337	= { FOLLOW_sentence_lv23456_in_sentence337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_lv23456382  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_lv23456382_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_lv23456382	= { FOLLOW_idtf_in_sentence_lv23456382_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_sentence_lv23456408  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_sentence_lv23456408_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_sentence_lv23456408	= { FOLLOW_CONNECTORS_in_sentence_lv23456408_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrsList_in_sentence_lv23456429  */
static	ANTLR3_BITWORD FOLLOW_attrsList_in_sentence_lv23456429_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_attrsList_in_sentence_lv23456429	= { FOLLOW_attrsList_in_sentence_lv23456429_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_objectList_in_sentence_lv23456450  */
static	ANTLR3_BITWORD FOLLOW_objectList_in_sentence_lv23456450_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_objectList_in_sentence_lv23456450	= { FOLLOW_objectList_in_sentence_lv23456450_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_in_sentence_lv1501  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_in_sentence_lv1501_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000000) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_in_sentence_lv1501	= { FOLLOW_simpleIdtf_in_sentence_lv1501_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TRIPLESEP_in_sentence_lv1521  */
static	ANTLR3_BITWORD FOLLOW_TRIPLESEP_in_sentence_lv1521_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002010000) };
static  ANTLR3_BITSET_LIST FOLLOW_TRIPLESEP_in_sentence_lv1521	= { FOLLOW_TRIPLESEP_in_sentence_lv1521_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_in_sentence_lv1543  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_in_sentence_lv1543_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000000) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_in_sentence_lv1543	= { FOLLOW_simpleIdtf_in_sentence_lv1543_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TRIPLESEP_in_sentence_lv1563  */
static	ANTLR3_BITWORD FOLLOW_TRIPLESEP_in_sentence_lv1563_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002010000) };
static  ANTLR3_BITSET_LIST FOLLOW_TRIPLESEP_in_sentence_lv1563	= { FOLLOW_TRIPLESEP_in_sentence_lv1563_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_in_sentence_lv1584  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_in_sentence_lv1584_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_in_sentence_lv1584	= { FOLLOW_simpleIdtf_in_sentence_lv1584_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_attrsep_in_attrsList632  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_attrsep_in_attrsList632_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002010002) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_attrsep_in_attrsList632	= { FOLLOW_simpleIdtf_attrsep_in_attrsList632_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_in_simpleIdtf_attrsep681  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_in_simpleIdtf_attrsep681_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_in_simpleIdtf_attrsep681	= { FOLLOW_simpleIdtf_in_simpleIdtf_attrsep681_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ATTRSEP_in_simpleIdtf_attrsep697  */
static	ANTLR3_BITWORD FOLLOW_ATTRSEP_in_simpleIdtf_attrsep697_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ATTRSEP_in_simpleIdtf_attrsep697	= { FOLLOW_ATTRSEP_in_simpleIdtf_attrsep697_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtfWithInt_in_objectList756  */
static	ANTLR3_BITWORD FOLLOW_idtfWithInt_in_objectList756_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtfWithInt_in_objectList756	= { FOLLOW_idtfWithInt_in_objectList756_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_objsep_IdtfWithInt_in_objectList784  */
static	ANTLR3_BITWORD FOLLOW_objsep_IdtfWithInt_in_objectList784_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_objsep_IdtfWithInt_in_objectList784	= { FOLLOW_objsep_IdtfWithInt_in_objectList784_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OBJSEP_in_objsep_IdtfWithInt832  */
static	ANTLR3_BITWORD FOLLOW_OBJSEP_in_objsep_IdtfWithInt832_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_OBJSEP_in_objsep_IdtfWithInt832	= { FOLLOW_OBJSEP_in_objsep_IdtfWithInt832_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtfWithInt_in_objsep_IdtfWithInt854  */
static	ANTLR3_BITWORD FOLLOW_idtfWithInt_in_objsep_IdtfWithInt854_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtfWithInt_in_objsep_IdtfWithInt854	= { FOLLOW_idtfWithInt_in_objsep_IdtfWithInt854_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_intSentence905  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_intSentence905_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_intSentence905	= { FOLLOW_CONNECTORS_in_intSentence905_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrsList_in_intSentence926  */
static	ANTLR3_BITWORD FOLLOW_attrsList_in_intSentence926_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_attrsList_in_intSentence926	= { FOLLOW_attrsList_in_intSentence926_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_objectList_in_intSentence948  */
static	ANTLR3_BITWORD FOLLOW_objectList_in_intSentence948_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_objectList_in_intSentence948	= { FOLLOW_objectList_in_intSentence948_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAR_INT_in_intSentenceList1000  */
static	ANTLR3_BITWORD FOLLOW_LPAR_INT_in_intSentenceList1000_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAR_INT_in_intSentenceList1000	= { FOLLOW_LPAR_INT_in_intSentenceList1000_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_intSentence_sentsep_in_intSentenceList1035  */
static	ANTLR3_BITWORD FOLLOW_intSentence_sentsep_in_intSentenceList1035_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080080) };
static  ANTLR3_BITSET_LIST FOLLOW_intSentence_sentsep_in_intSentenceList1035	= { FOLLOW_intSentence_sentsep_in_intSentenceList1035_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAR_INT_in_intSentenceList1065  */
static	ANTLR3_BITWORD FOLLOW_RPAR_INT_in_intSentenceList1065_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAR_INT_in_intSentenceList1065	= { FOLLOW_RPAR_INT_in_intSentenceList1065_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_intSentence_in_intSentence_sentsep1123  */
static	ANTLR3_BITWORD FOLLOW_intSentence_in_intSentence_sentsep1123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_intSentence_in_intSentence_sentsep1123	= { FOLLOW_intSentence_in_intSentence_sentsep1123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SENTSEP_in_intSentence_sentsep1147  */
static	ANTLR3_BITWORD FOLLOW_SENTSEP_in_intSentence_sentsep1147_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SENTSEP_in_intSentence_sentsep1147	= { FOLLOW_SENTSEP_in_intSentence_sentsep1147_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_intSentenceList_in_internal1200  */
static	ANTLR3_BITWORD FOLLOW_intSentenceList_in_internal1200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_intSentenceList_in_internal1200	= { FOLLOW_intSentenceList_in_internal1200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAR_in_triple1256  */
static	ANTLR3_BITWORD FOLLOW_LPAR_in_triple1256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAR_in_triple1256	= { FOLLOW_LPAR_in_triple1256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_triple1279  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_triple1279_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_triple1279	= { FOLLOW_idtf_in_triple1279_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONTENT_in_triple1301  */
static	ANTLR3_BITWORD FOLLOW_CONTENT_in_triple1301_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_CONTENT_in_triple1301	= { FOLLOW_CONTENT_in_triple1301_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_triple1321  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_triple1321_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_triple1321	= { FOLLOW_idtf_in_triple1321_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAR_in_triple1343  */
static	ANTLR3_BITWORD FOLLOW_RPAR_in_triple1343_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAR_in_triple1343	= { FOLLOW_RPAR_in_triple1343_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ALIASNONAME_in_alias1396  */
static	ANTLR3_BITWORD FOLLOW_ALIASNONAME_in_alias1396_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ALIASNONAME_in_alias1396	= { FOLLOW_ALIASNONAME_in_alias1396_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAR_SET_in_setIdtf1455  */
static	ANTLR3_BITWORD FOLLOW_LPAR_SET_in_setIdtf1455_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAR_SET_in_setIdtf1455	= { FOLLOW_LPAR_SET_in_setIdtf1455_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrsList_in_setIdtf1502  */
static	ANTLR3_BITWORD FOLLOW_attrsList_in_setIdtf1502_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_attrsList_in_setIdtf1502	= { FOLLOW_attrsList_in_setIdtf1502_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtfWithInt_in_setIdtf1548  */
static	ANTLR3_BITWORD FOLLOW_idtfWithInt_in_setIdtf1548_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000220000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtfWithInt_in_setIdtf1548	= { FOLLOW_idtfWithInt_in_setIdtf1548_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_objsep_AttrsList_idtfWithInt_in_setIdtf1593  */
static	ANTLR3_BITWORD FOLLOW_objsep_AttrsList_idtfWithInt_in_setIdtf1593_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000220000) };
static  ANTLR3_BITSET_LIST FOLLOW_objsep_AttrsList_idtfWithInt_in_setIdtf1593	= { FOLLOW_objsep_AttrsList_idtfWithInt_in_setIdtf1593_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAR_SET_in_setIdtf1623  */
static	ANTLR3_BITWORD FOLLOW_RPAR_SET_in_setIdtf1623_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAR_SET_in_setIdtf1623	= { FOLLOW_RPAR_SET_in_setIdtf1623_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OBJSEP_in_objsep_AttrsList_idtfWithInt1690  */
static	ANTLR3_BITWORD FOLLOW_OBJSEP_in_objsep_AttrsList_idtfWithInt1690_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_OBJSEP_in_objsep_AttrsList_idtfWithInt1690	= { FOLLOW_OBJSEP_in_objsep_AttrsList_idtfWithInt1690_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrsList_in_objsep_AttrsList_idtfWithInt1713  */
static	ANTLR3_BITWORD FOLLOW_attrsList_in_objsep_AttrsList_idtfWithInt1713_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_attrsList_in_objsep_AttrsList_idtfWithInt1713	= { FOLLOW_attrsList_in_objsep_AttrsList_idtfWithInt1713_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtfWithInt_in_objsep_AttrsList_idtfWithInt1732  */
static	ANTLR3_BITWORD FOLLOW_idtfWithInt_in_objsep_AttrsList_idtfWithInt1732_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtfWithInt_in_objsep_AttrsList_idtfWithInt1732	= { FOLLOW_idtfWithInt_in_objsep_AttrsList_idtfWithInt1732_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAR_OSET_in_osetIdtf1787  */
static	ANTLR3_BITWORD FOLLOW_LPAR_OSET_in_osetIdtf1787_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAR_OSET_in_osetIdtf1787	= { FOLLOW_LPAR_OSET_in_osetIdtf1787_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrsList_in_osetIdtf1836  */
static	ANTLR3_BITWORD FOLLOW_attrsList_in_osetIdtf1836_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002016910) };
static  ANTLR3_BITSET_LIST FOLLOW_attrsList_in_osetIdtf1836	= { FOLLOW_attrsList_in_osetIdtf1836_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtfWithInt_in_osetIdtf1885  */
static	ANTLR3_BITWORD FOLLOW_idtfWithInt_in_osetIdtf1885_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000120000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtfWithInt_in_osetIdtf1885	= { FOLLOW_idtfWithInt_in_osetIdtf1885_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_objsep_AttrsList_idtfWithInt_in_osetIdtf1934  */
static	ANTLR3_BITWORD FOLLOW_objsep_AttrsList_idtfWithInt_in_osetIdtf1934_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000120000) };
static  ANTLR3_BITSET_LIST FOLLOW_objsep_AttrsList_idtfWithInt_in_osetIdtf1934	= { FOLLOW_objsep_AttrsList_idtfWithInt_in_osetIdtf1934_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAR_OSET_in_osetIdtf1969  */
static	ANTLR3_BITWORD FOLLOW_RPAR_OSET_in_osetIdtf1969_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAR_OSET_in_osetIdtf1969	= { FOLLOW_RPAR_OSET_in_osetIdtf1969_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleIdtf_in_anyIdtf2043  */
static	ANTLR3_BITWORD FOLLOW_simpleIdtf_in_anyIdtf2043_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleIdtf_in_anyIdtf2043	= { FOLLOW_simpleIdtf_in_anyIdtf2043_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONTENT_in_anyIdtf2062  */
static	ANTLR3_BITWORD FOLLOW_CONTENT_in_anyIdtf2062_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_CONTENT_in_anyIdtf2062	= { FOLLOW_CONTENT_in_anyIdtf2062_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_triple_in_anyIdtf2084  */
static	ANTLR3_BITWORD FOLLOW_triple_in_anyIdtf2084_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_triple_in_anyIdtf2084	= { FOLLOW_triple_in_anyIdtf2084_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_setIdtf_in_anyIdtf2107  */
static	ANTLR3_BITWORD FOLLOW_setIdtf_in_anyIdtf2107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_setIdtf_in_anyIdtf2107	= { FOLLOW_setIdtf_in_anyIdtf2107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_osetIdtf_in_anyIdtf2129  */
static	ANTLR3_BITWORD FOLLOW_osetIdtf_in_anyIdtf2129_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_osetIdtf_in_anyIdtf2129	= { FOLLOW_osetIdtf_in_anyIdtf2129_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_alias_in_anyIdtf2150  */
static	ANTLR3_BITWORD FOLLOW_alias_in_anyIdtf2150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_alias_in_anyIdtf2150	= { FOLLOW_alias_in_anyIdtf2150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_anyIdtf_in_idtf2214  */
static	ANTLR3_BITWORD FOLLOW_anyIdtf_in_idtf2214_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_anyIdtf_in_idtf2214	= { FOLLOW_anyIdtf_in_idtf2214_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_simpleIdtf2266  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_simpleIdtf2266_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_simpleIdtf2266	= { FOLLOW_NAME_in_simpleIdtf2266_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_URL_in_simpleIdtf2282  */
static	ANTLR3_BITWORD FOLLOW_URL_in_simpleIdtf2282_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_URL_in_simpleIdtf2282	= { FOLLOW_URL_in_simpleIdtf2282_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtfWithInt2331  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtfWithInt2331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtfWithInt2331	= { FOLLOW_idtf_in_idtfWithInt2331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_internal_in_idtfWithInt2355  */
static	ANTLR3_BITWORD FOLLOW_internal_in_idtfWithInt2355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_internal_in_idtfWithInt2355	= { FOLLOW_internal_in_idtfWithInt2355_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start syntax
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:102:1: syntax : ( (a= sentence_sentsep ) | (b= KEYWORD ) )* EOF ;
 */
static void
syntax(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */



    		  //mNeedRecover = false;
    		  //SyntaxAST* retPtr = new SyntaxAST();
    		  //INIT_RULE(retPtr);
    		  //mHasException = false;
    		  //mLastExceptionCheked = true;
    		  
            SetParserNeedRecover(ANTLR3_FALSE);
        SetParserNeedReturn(ANTLR3_FALSE);
    		  
    		
    b       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:118:3: ( ( (a= sentence_sentsep ) | (b= KEYWORD ) )* EOF )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:119:3: ( (a= sentence_sentsep ) | (b= KEYWORD ) )* EOF
        {
            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:119:3: ( (a= sentence_sentsep ) | (b= KEYWORD ) )*

            for (;;)
            {
                int alt1=3;
                switch ( LA(1) )
                {
                case ALIASNONAME:
                case CONTENT:
                case LPAR:
                case LPAR_OSET:
                case LPAR_SET:
                case NAME:
                case URL:
                	{
                		alt1=1;
                	}
                    break;
                case KEYWORD:
                	{
                		alt1=2;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:120:5: (a= sentence_sentsep )
            	    {
            	        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:120:5: (a= sentence_sentsep )
            	        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:120:7: a= sentence_sentsep
            	        {
            	            {
            	                BNTS(a)
            	            }


            	            FOLLOWPUSH(FOLLOW_sentence_sentsep_in_syntax118);
            	            sentence_sentsep(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulesyntaxEx;
            	            }


            	            {
            	                 
            	                						        if(ParserNeedRecover())
            	                						            ParserRecover(ctx->pParser->rec);
                                                                SetParserNeedReturn(ANTLR3_FALSE);
            	                						      
            	            }


            	        }


            	    }
            	    break;
            	case 2:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:128:5: (b= KEYWORD )
            	    {
            	        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:128:5: (b= KEYWORD )
            	        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:129:7: b= KEYWORD
            	        {
            	            b = (pANTLR3_COMMON_TOKEN) MATCHT(KEYWORD, &FOLLOW_KEYWORD_in_syntax170);
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulesyntaxEx;
            	            }


            	            {
            	                 
            	                                  if(ParserNeedRecover())
            	                                      ParserRecover(ctx->pParser->rec);
                                                  SetParserNeedReturn(ANTLR3_FALSE);
            	                                
            	            }


            	        }


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


             MATCHT(EOF, &FOLLOW_EOF_in_syntax203);
            if  (HASEXCEPTION())
            {
                goto rulesyntaxEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesyntaxEx; /* Prevent compiler warnings */
    rulesyntaxEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end syntax */

/**
 * $ANTLR start sentence_sentsep
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:140:1: sentence_sentsep :a= sentence b= SENTSEP ;
 */
static void
sentence_sentsep(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    		    //retPtr = new SentenceWithSeparator();
    		    INIT_RULE(retPtr);
    		
    b       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:149:5: (a= sentence b= SENTSEP )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:150:5: a= sentence b= SENTSEP
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_sentence_in_sentence_sentsep247);
            sentence(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_sentsepEx;
            }


            {
                 ANTS(a,setSentence)
            }


            {
                BTS(b) 
            }


            b = (pANTLR3_COMMON_TOKEN) MATCHT(SENTSEP, &FOLLOW_SENTSEP_in_sentence_sentsep262);
            if  (HASEXCEPTION())
            {
                goto rulesentence_sentsepEx;
            }


            {
                 ATS(b,setSeparator)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesentence_sentsepEx; /* Prevent compiler warnings */
    rulesentence_sentsepEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end sentence_sentsep */

/**
 * $ANTLR start sentence
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:154:1: sentence : (a= sentence_lv1 |b= sentence_lv23456 );
 */
static void
sentence(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    		  //retPtr = new SentenceAST();
    		  INIT_RULE(retPtr);
    		
    {
        {
            //  D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:163:9: (a= sentence_lv1 |b= sentence_lv23456 )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case NAME:
            	{
            		switch ( LA(2) )
            		{
            		case TRIPLESEP:
            			{
            				alt2=1;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulesentenceEx;

            		}

            	}
                break;
            case URL:
            	{
            		switch ( LA(2) )
            		{
            		case TRIPLESEP:
            			{
            				alt2=1;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 2;


            		    goto rulesentenceEx;

            		}

            	}
                break;
            case ALIASNONAME:
            case CONTENT:
            case LPAR:
            case LPAR_OSET:
            case LPAR_SET:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulesentenceEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:164:9: a= sentence_lv1
        	    {
        	        {
        	            BNTS(a)
        	        }


        	        FOLLOWPUSH(FOLLOW_sentence_lv1_in_sentence311);
        	        sentence_lv1(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }


        	        {
        	            ANTS(a,addSentenceLvl1)
        	        }


        	    }
        	    break;
        	case 2:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:165:9: b= sentence_lv23456
        	    {
        	        {
        	            BNTS(b)
        	        }


        	        FOLLOWPUSH(FOLLOW_sentence_lv23456_in_sentence337);
        	        sentence_lv23456(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }


        	        {
        	            ANTS(b,addSentenceLv234561)
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulesentenceEx; /* Prevent compiler warnings */
    rulesentenceEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end sentence */

/**
 * $ANTLR start sentence_lv23456
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:169:1: sentence_lv23456 :a= idtf b= CONNECTORS c= attrsList d= objectList ;
 */
static void
sentence_lv23456(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    		  //retPtr = new SentenceLv234561AST();
    		  INIT_RULE(retPtr);
    		
    b       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:178:5: (a= idtf b= CONNECTORS c= attrsList d= objectList )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:179:5: a= idtf b= CONNECTORS c= attrsList d= objectList
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_idtf_in_sentence_lv23456382);
            idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv23456Ex;
            }


            {
                 ANTS(a,setIdentifier)
            }


            {
                BTS(b) 
            }


            b = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_sentence_lv23456408);
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv23456Ex;
            }


            {
                 ATS(b,setConnector)
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_attrsList_in_sentence_lv23456429);
            attrsList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv23456Ex;
            }


            {
                 ANTS(c,setAttributeList)
            }


            {
                BNTS(d)
            }


            FOLLOWPUSH(FOLLOW_objectList_in_sentence_lv23456450);
            objectList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv23456Ex;
            }


            {
                 ANTS(d,setObjectList) 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesentence_lv23456Ex; /* Prevent compiler warnings */
    rulesentence_lv23456Ex: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end sentence_lv23456 */

/**
 * $ANTLR start sentence_lv1
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:187:1: sentence_lv1 :a= simpleIdtf b= TRIPLESEP c= simpleIdtf d= TRIPLESEP e= simpleIdtf ;
 */
static void
sentence_lv1(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;
    pANTLR3_COMMON_TOKEN    d;

    /* Initialize rule variables
     */


    		  //retPtr = new SentenceLvl1AST();
    		  INIT_RULE(retPtr);
    		
    b       = NULL;
    d       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:196:6: (a= simpleIdtf b= TRIPLESEP c= simpleIdtf d= TRIPLESEP e= simpleIdtf )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:197:6: a= simpleIdtf b= TRIPLESEP c= simpleIdtf d= TRIPLESEP e= simpleIdtf
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_simpleIdtf_in_sentence_lv1501);
            simpleIdtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv1Ex;
            }


            {
                 ANTS(a,setFirstIdentifier)
            }


            {
                BTS(b) 
            }


            b = (pANTLR3_COMMON_TOKEN) MATCHT(TRIPLESEP, &FOLLOW_TRIPLESEP_in_sentence_lv1521);
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv1Ex;
            }


            {
                 ATS(b,setFirstTripleSeparator)
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_simpleIdtf_in_sentence_lv1543);
            simpleIdtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv1Ex;
            }


            {
                 ANTS(c,setSecondIdentifier)
            }


            {
                BTS(d) 
            }


            d = (pANTLR3_COMMON_TOKEN) MATCHT(TRIPLESEP, &FOLLOW_TRIPLESEP_in_sentence_lv1563);
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv1Ex;
            }


            {
                 ATS(d,setSecondTripleSeparator)
            }


            {
                BNTS(e)
            }


            FOLLOWPUSH(FOLLOW_simpleIdtf_in_sentence_lv1584);
            simpleIdtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_lv1Ex;
            }


            {
                 ANTS(e,setThirdIdentifier)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesentence_lv1Ex; /* Prevent compiler warnings */
    rulesentence_lv1Ex: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end sentence_lv1 */

/**
 * $ANTLR start attrsList
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:205:1: attrsList : (a= simpleIdtf_attrsep )* ;
 */
static void
attrsList(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    		  //retPtr = new AttributesListAST();
    		  INIT_RULE(retPtr);
    		
    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:213:7: ( (a= simpleIdtf_attrsep )* )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:214:7: (a= simpleIdtf_attrsep )*
        {
            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:214:7: (a= simpleIdtf_attrsep )*

            for (;;)
            {
                int alt3=2;
                switch ( LA(1) )
                {
                case NAME:
                	{
                		switch ( LA(2) )
                		{
                		case ATTRSEP:
                			{
                				alt3=1;
                			}
                		    break;

                		}

                	}
                    break;
                case URL:
                	{
                		switch ( LA(2) )
                		{
                		case ATTRSEP:
                			{
                				alt3=1;
                			}
                		    break;

                		}

                	}
                    break;

                }

                switch (alt3)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:214:9: a= simpleIdtf_attrsep
            	    {
            	        {
            	            BNTS(a)
            	        }


            	        FOLLOWPUSH(FOLLOW_simpleIdtf_attrsep_in_attrsList632);
            	        simpleIdtf_attrsep(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrsListEx;
            	        }


            	        {
            	            ANTS(a,addIdentifier)
            	        }


            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleattrsListEx; /* Prevent compiler warnings */
    ruleattrsListEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end attrsList */

/**
 * $ANTLR start simpleIdtf_attrsep
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:218:1: simpleIdtf_attrsep :a= simpleIdtf b= ATTRSEP ;
 */
static void
simpleIdtf_attrsep(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    	    //retPtr = new SimpleIdtfrWAttrSepAST();
    	    INIT_RULE(retPtr);
    	  
    b       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:226:5: (a= simpleIdtf b= ATTRSEP )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:227:5: a= simpleIdtf b= ATTRSEP
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_simpleIdtf_in_simpleIdtf_attrsep681);
            simpleIdtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesimpleIdtf_attrsepEx;
            }


            {
                 ANTS(a,setIdentifier)
            }


            {
                BTS(b) 
            }


            b = (pANTLR3_COMMON_TOKEN) MATCHT(ATTRSEP, &FOLLOW_ATTRSEP_in_simpleIdtf_attrsep697);
            if  (HASEXCEPTION())
            {
                goto rulesimpleIdtf_attrsepEx;
            }


            {
                 ATS(b,setAttributeSeparator)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesimpleIdtf_attrsepEx; /* Prevent compiler warnings */
    rulesimpleIdtf_attrsepEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end simpleIdtf_attrsep */

/**
 * $ANTLR start objectList
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:232:1: objectList :a= idtfWithInt (b= objsep_IdtfWithInt )* ;
 */
static void
objectList(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    		  //retPtr = new ObjectListAST();
    		  INIT_RULE(retPtr);
    		
    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:240:11: (a= idtfWithInt (b= objsep_IdtfWithInt )* )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:241:11: a= idtfWithInt (b= objsep_IdtfWithInt )*
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_idtfWithInt_in_objectList756);
            idtfWithInt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobjectListEx;
            }


            {
                 ANTS(a,setIdentifierWithInt)
            }


            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:242:9: (b= objsep_IdtfWithInt )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case OBJSEP:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:242:11: b= objsep_IdtfWithInt
            	    {
            	        {
            	            BNTS(b)
            	        }


            	        FOLLOWPUSH(FOLLOW_objsep_IdtfWithInt_in_objectList784);
            	        objsep_IdtfWithInt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleobjectListEx;
            	        }


            	        {
            	             ANTS(b,addIdentifier)
            	        }


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleobjectListEx; /* Prevent compiler warnings */
    ruleobjectListEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end objectList */

/**
 * $ANTLR start objsep_IdtfWithInt
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:247:1: objsep_IdtfWithInt :a= OBJSEP b= idtfWithInt ;
 */
static void
objsep_IdtfWithInt(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    	    //retPtr = new ObjSepWIdtfWithInt();
    	    INIT_RULE(retPtr);
    	  
    a       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:255:5: (a= OBJSEP b= idtfWithInt )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:256:5: a= OBJSEP b= idtfWithInt
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(OBJSEP, &FOLLOW_OBJSEP_in_objsep_IdtfWithInt832);
            if  (HASEXCEPTION())
            {
                goto ruleobjsep_IdtfWithIntEx;
            }


            {
                 ATS(a,setObjectSeparator)
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_idtfWithInt_in_objsep_IdtfWithInt854);
            idtfWithInt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobjsep_IdtfWithIntEx;
            }


            {
                 ANTS(b,setIdentifierWithInternal)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleobjsep_IdtfWithIntEx; /* Prevent compiler warnings */
    ruleobjsep_IdtfWithIntEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end objsep_IdtfWithInt */

/**
 * $ANTLR start intSentence
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:261:1: intSentence :a= CONNECTORS b= attrsList c= objectList ;
 */
static void
intSentence(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    		  //retPtr = new InternalSentenceAST();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:269:9: (a= CONNECTORS b= attrsList c= objectList )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:270:9: a= CONNECTORS b= attrsList c= objectList
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_intSentence905);
            if  (HASEXCEPTION())
            {
                goto ruleintSentenceEx;
            }


            {
                 ATS(a,setConnector)
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_attrsList_in_intSentence926);
            attrsList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleintSentenceEx;
            }


            {
                 ANTS(b,setAttributeList)
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_objectList_in_intSentence948);
            objectList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleintSentenceEx;
            }


            {
                 ANTS(c,setObjectList)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleintSentenceEx; /* Prevent compiler warnings */
    ruleintSentenceEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end intSentence */

/**
 * $ANTLR start intSentenceList
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:276:1: intSentenceList :a= LPAR_INT (b= intSentence_sentsep )+ c= RPAR_INT ;
 */
static void
intSentenceList(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    c;

    /* Initialize rule variables
     */


    		  //retPtr = new InternalSentenceListAST();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;
    c       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:284:11: (a= LPAR_INT (b= intSentence_sentsep )+ c= RPAR_INT )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:285:11: a= LPAR_INT (b= intSentence_sentsep )+ c= RPAR_INT
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(LPAR_INT, &FOLLOW_LPAR_INT_in_intSentenceList1000);
            if  (HASEXCEPTION())
            {
                goto ruleintSentenceListEx;
            }


            {
                 ATS(a,setLeftInternalSeparator)
            }


            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:286:9: (b= intSentence_sentsep )+
            {
                int cnt5=0;

                for (;;)
                {
                    int alt5=2;
            	switch ( LA(1) )
            	{
            	case CONNECTORS:
            		{
            			alt5=1;
            		}
            	    break;

            	}

            	switch (alt5)
            	{
            	    case 1:
            	        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:286:11: b= intSentence_sentsep
            	        {
            	            {
            	                BNTS(b)
            	            }


            	            FOLLOWPUSH(FOLLOW_intSentence_sentsep_in_intSentenceList1035);
            	            intSentence_sentsep(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleintSentenceListEx;
            	            }


            	            {
            	                 ANTS(b,addSentence)
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt5 >= 1 )
            		{
            		    goto loop5;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleintSentenceListEx;
            	}
            	cnt5++;
                }
                loop5: ;	/* Jump to here if this rule does not match */
            }

            {
                BTS(c) 
            }


            c = (pANTLR3_COMMON_TOKEN) MATCHT(RPAR_INT, &FOLLOW_RPAR_INT_in_intSentenceList1065);
            if  (HASEXCEPTION())
            {
                goto ruleintSentenceListEx;
            }


            {
                 ATS(c,setRigthInternalSeparator)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleintSentenceListEx; /* Prevent compiler warnings */
    ruleintSentenceListEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end intSentenceList */

/**
 * $ANTLR start intSentence_sentsep
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:290:1: intSentence_sentsep :a= intSentence b= SENTSEP ;
 */
static void
intSentence_sentsep(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    		  //retPtr = new IntSentenceWSentSep();
    		  INIT_RULE(retPtr);
    		
    b       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:298:5: (a= intSentence b= SENTSEP )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:299:5: a= intSentence b= SENTSEP
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_intSentence_in_intSentence_sentsep1123);
            intSentence(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleintSentence_sentsepEx;
            }


            {
                 ANTS(a,setInternalSentence)
            }


            {
                BTS(b) 
            }


            b = (pANTLR3_COMMON_TOKEN) MATCHT(SENTSEP, &FOLLOW_SENTSEP_in_intSentence_sentsep1147);
            if  (HASEXCEPTION())
            {
                goto ruleintSentence_sentsepEx;
            }


            {
                 ATS(b,setSentenceSeparator)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleintSentence_sentsepEx; /* Prevent compiler warnings */
    ruleintSentence_sentsepEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end intSentence_sentsep */

/**
 * $ANTLR start internal
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:303:1: internal :a= intSentenceList ;
 */
static void
internal(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    		  //retPtr = new InternalAST();
    		  INIT_RULE(retPtr);
    		
    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:311:4: (a= intSentenceList )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:312:4: a= intSentenceList
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_intSentenceList_in_internal1200);
            intSentenceList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleinternalEx;
            }


            {
                 ANTS(a,setInternalSentenceList)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleinternalEx; /* Prevent compiler warnings */
    ruleinternalEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end internal */

/**
 * $ANTLR start triple
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:315:1: triple :a= LPAR b= idtf c= CONTENT d= idtf e= RPAR ;
 */
static void
triple(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    c;
    pANTLR3_COMMON_TOKEN    e;

    /* Initialize rule variables
     */


          //retPtr = new TripleAST();
          INIT_RULE(retPtr);
        
    a       = NULL;
    c       = NULL;
    e       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:323:7: (a= LPAR b= idtf c= CONTENT d= idtf e= RPAR )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:324:7: a= LPAR b= idtf c= CONTENT d= idtf e= RPAR
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(LPAR, &FOLLOW_LPAR_in_triple1256);
            if  (HASEXCEPTION())
            {
                goto ruletripleEx;
            }


            {
                 ATS(a,setLeftPar)
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_idtf_in_triple1279);
            idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletripleEx;
            }


            {
                 ANTS(b,setFirstIdentifier)
            }


            {
                BTS(c) 
            }


            c = (pANTLR3_COMMON_TOKEN) MATCHT(CONTENT, &FOLLOW_CONTENT_in_triple1301);
            if  (HASEXCEPTION())
            {
                goto ruletripleEx;
            }


            {
                 ATS(c,setContent)
            }


            {
                BNTS(d)
            }


            FOLLOWPUSH(FOLLOW_idtf_in_triple1321);
            idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletripleEx;
            }


            {
                 ANTS(d,setSecondIdentifier)
            }


            {
                BTS(e) 
            }


            e = (pANTLR3_COMMON_TOKEN) MATCHT(RPAR, &FOLLOW_RPAR_in_triple1343);
            if  (HASEXCEPTION())
            {
                goto ruletripleEx;
            }


            {
                 ATS(e,setRighPar)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletripleEx; /* Prevent compiler warnings */
    ruletripleEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end triple */

/**
 * $ANTLR start alias
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:331:1: alias :a= ALIASNONAME ;
 */
static void
alias(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    		  //retPtr = new AliasAST();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:340:7: (a= ALIASNONAME )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:341:7: a= ALIASNONAME
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(ALIASNONAME, &FOLLOW_ALIASNONAME_in_alias1396);
            if  (HASEXCEPTION())
            {
                goto rulealiasEx;
            }


            {
                 ATS(a,setAlias)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulealiasEx; /* Prevent compiler warnings */
    rulealiasEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end alias */

/**
 * $ANTLR start setIdtf
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:345:1: setIdtf :a= LPAR_SET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_SET ;
 */
static void
setIdtf(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    e;

    /* Initialize rule variables
     */


    		  //retPtr = new SetIdentifierAST();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;
    e       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:353:9: (a= LPAR_SET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_SET )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:354:9: a= LPAR_SET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_SET
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(LPAR_SET, &FOLLOW_LPAR_SET_in_setIdtf1455);
            if  (HASEXCEPTION())
            {
                goto rulesetIdtfEx;
            }


            {
                 ATS(a,setLeftSeparator) 
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_attrsList_in_setIdtf1502);
            attrsList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesetIdtfEx;
            }


            {
                 ANTS(b,setAttributeList) 
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_idtfWithInt_in_setIdtf1548);
            idtfWithInt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesetIdtfEx;
            }


            {
                 ANTS(c,setIdentifier) 
            }


            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:357:7: (d= objsep_AttrsList_idtfWithInt )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case OBJSEP:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:357:9: d= objsep_AttrsList_idtfWithInt
            	    {
            	        {
            	            BNTS(d)
            	        }


            	        FOLLOWPUSH(FOLLOW_objsep_AttrsList_idtfWithInt_in_setIdtf1593);
            	        objsep_AttrsList_idtfWithInt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesetIdtfEx;
            	        }


            	        {
            	             ANTS(d,addSentence) 
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


            {
                BTS(e) 
            }


            e = (pANTLR3_COMMON_TOKEN) MATCHT(RPAR_SET, &FOLLOW_RPAR_SET_in_setIdtf1623);
            if  (HASEXCEPTION())
            {
                goto rulesetIdtfEx;
            }


            {
                 ATS(e,setRightSeparator)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesetIdtfEx; /* Prevent compiler warnings */
    rulesetIdtfEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end setIdtf */

/**
 * $ANTLR start objsep_AttrsList_idtfWithInt
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:361:1: objsep_AttrsList_idtfWithInt :a= OBJSEP b= attrsList c= idtfWithInt ;
 */
static void
objsep_AttrsList_idtfWithInt(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;

    /* Initialize rule variables
     */


    		  //retPtr = new ObjSepWAttrListWIdtfWithInt();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:369:4: (a= OBJSEP b= attrsList c= idtfWithInt )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:370:4: a= OBJSEP b= attrsList c= idtfWithInt
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(OBJSEP, &FOLLOW_OBJSEP_in_objsep_AttrsList_idtfWithInt1690);
            if  (HASEXCEPTION())
            {
                goto ruleobjsep_AttrsList_idtfWithIntEx;
            }


            {
                 ATS(a,setSeparator)
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_attrsList_in_objsep_AttrsList_idtfWithInt1713);
            attrsList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobjsep_AttrsList_idtfWithIntEx;
            }


            {
                 ANTS(b,setAttributeList)
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_idtfWithInt_in_objsep_AttrsList_idtfWithInt1732);
            idtfWithInt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobjsep_AttrsList_idtfWithIntEx;
            }


            {
                 ANTS(c,setIdentifier)
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleobjsep_AttrsList_idtfWithIntEx; /* Prevent compiler warnings */
    ruleobjsep_AttrsList_idtfWithIntEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end objsep_AttrsList_idtfWithInt */

/**
 * $ANTLR start osetIdtf
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:376:1: osetIdtf :a= LPAR_OSET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_OSET ;
 */
static void
osetIdtf(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    e;

    /* Initialize rule variables
     */


    		  //retPtr = new OSetIdentifierAST();
    		  INIT_RULE(retPtr);
    		
    a       = NULL;
    e       = NULL;

    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:384:9: (a= LPAR_OSET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_OSET )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:385:9: a= LPAR_OSET b= attrsList c= idtfWithInt (d= objsep_AttrsList_idtfWithInt )* e= RPAR_OSET
        {
            {
                BTS(a) 
            }


            a = (pANTLR3_COMMON_TOKEN) MATCHT(LPAR_OSET, &FOLLOW_LPAR_OSET_in_osetIdtf1787);
            if  (HASEXCEPTION())
            {
                goto ruleosetIdtfEx;
            }


            {
                 ATS(a,setLeftSeparator)   
            }


            {
                BNTS(b)
            }


            FOLLOWPUSH(FOLLOW_attrsList_in_osetIdtf1836);
            attrsList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleosetIdtfEx;
            }


            {
                 ANTS(b,setAttributeList)  
            }


            {
                BNTS(c)
            }


            FOLLOWPUSH(FOLLOW_idtfWithInt_in_osetIdtf1885);
            idtfWithInt(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleosetIdtfEx;
            }


            {
                 ANTS(c,setIdentifier)      
            }


            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:388:7: (d= objsep_AttrsList_idtfWithInt )*

            for (;;)
            {
                int alt7=2;
                switch ( LA(1) )
                {
                case OBJSEP:
                	{
                		alt7=1;
                	}
                    break;

                }

                switch (alt7)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:388:9: d= objsep_AttrsList_idtfWithInt
            	    {
            	        {
            	            BNTS(d)
            	        }


            	        FOLLOWPUSH(FOLLOW_objsep_AttrsList_idtfWithInt_in_osetIdtf1934);
            	        objsep_AttrsList_idtfWithInt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleosetIdtfEx;
            	        }


            	        {
            	             ANTS(d,addSentence)    
            	        }


            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */


            {
                BTS(e) 
            }


            e = (pANTLR3_COMMON_TOKEN) MATCHT(RPAR_OSET, &FOLLOW_RPAR_OSET_in_osetIdtf1969);
            if  (HASEXCEPTION())
            {
                goto ruleosetIdtfEx;
            }


            {
                 ATS(e,setRightSeparator)               
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleosetIdtfEx; /* Prevent compiler warnings */
    ruleosetIdtfEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end osetIdtf */

/**
 * $ANTLR start anyIdtf
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:392:1: anyIdtf : (a= simpleIdtf |b= CONTENT |c= triple |d= setIdtf |e= osetIdtf |f= alias );
 */
static void
anyIdtf(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    		  //retPtr = new AnyIdentifierAST();
    		  INIT_RULE(retPtr);
    		
    b       = NULL;

    {
        {
            //  D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:399:5: (a= simpleIdtf |b= CONTENT |c= triple |d= setIdtf |e= osetIdtf |f= alias )

            ANTLR3_UINT32 alt8;

            alt8=6;

            switch ( LA(1) )
            {
            case NAME:
            case URL:
            	{
            		alt8=1;
            	}
                break;
            case CONTENT:
            	{
            		alt8=2;
            	}
                break;
            case LPAR:
            	{
            		alt8=3;
            	}
                break;
            case LPAR_SET:
            	{
            		alt8=4;
            	}
                break;
            case LPAR_OSET:
            	{
            		alt8=5;
            	}
                break;
            case ALIASNONAME:
            	{
            		alt8=6;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleanyIdtfEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:400:9: a= simpleIdtf
        	    {
        	        {
        	            BNTS(a)
        	        }


        	        FOLLOWPUSH(FOLLOW_simpleIdtf_in_anyIdtf2043);
        	        simpleIdtf(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ANTS(a,setSimpleIdentifier) 
        	        }


        	    }
        	    break;
        	case 2:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:401:9: b= CONTENT
        	    {
        	        {
        	            BTS(b) 
        	        }


        	        b = (pANTLR3_COMMON_TOKEN) MATCHT(CONTENT, &FOLLOW_CONTENT_in_anyIdtf2062);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ATS(b,setContent)           
        	        }


        	    }
        	    break;
        	case 3:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:402:9: c= triple
        	    {
        	        {
        	            BNTS(c)
        	        }


        	        FOLLOWPUSH(FOLLOW_triple_in_anyIdtf2084);
        	        triple(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ANTS(c,setTriple)           
        	        }


        	    }
        	    break;
        	case 4:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:403:9: d= setIdtf
        	    {
        	        {
        	            BNTS(d)
        	        }


        	        FOLLOWPUSH(FOLLOW_setIdtf_in_anyIdtf2107);
        	        setIdtf(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ANTS(d,setSetIdentifier)    
        	        }


        	    }
        	    break;
        	case 5:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:404:9: e= osetIdtf
        	    {
        	        {
        	            BNTS(e)
        	        }


        	        FOLLOWPUSH(FOLLOW_osetIdtf_in_anyIdtf2129);
        	        osetIdtf(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ANTS(e,setOSetIdentifier)   
        	        }


        	    }
        	    break;
        	case 6:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:405:9: f= alias
        	    {
        	        {
        	            BNTS(f)
        	        }


        	        FOLLOWPUSH(FOLLOW_alias_in_anyIdtf2150);
        	        alias(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleanyIdtfEx;
        	        }


        	        {
        	             ANTS(f,setAlias)            
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleanyIdtfEx; /* Prevent compiler warnings */
    ruleanyIdtfEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end anyIdtf */

/**
 * $ANTLR start idtf
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:410:1: idtf :a= anyIdtf ;
 */
static void
idtf(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    			  //retPtr = new IdentifierAST();
    			  INIT_RULE(retPtr);
    			
    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:417:5: (a= anyIdtf )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:418:5: a= anyIdtf
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_anyIdtf_in_idtf2214);
            anyIdtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtfEx;
            }


            {
                 ANTS(a,setIdentifier) 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleidtfEx; /* Prevent compiler warnings */
    ruleidtfEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end idtf */

/**
 * $ANTLR start simpleIdtf
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:421:1: simpleIdtf : (a= NAME |b= URL );
 */
static void
simpleIdtf(pSCsCParser ctx)
{
    pANTLR3_COMMON_TOKEN    a;
    pANTLR3_COMMON_TOKEN    b;

    /* Initialize rule variables
     */


    			  //retPtr = new SimpleIdentifierAST();
    			  INIT_RULE(retPtr);
    			
    a       = NULL;
    b       = NULL;

    {
        {
            //  D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:430:6: (a= NAME |b= URL )

            ANTLR3_UINT32 alt9;

            alt9=2;

            switch ( LA(1) )
            {
            case NAME:
            	{
            		alt9=1;
            	}
                break;
            case URL:
            	{
            		alt9=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 9;
                EXCEPTION->state        = 0;


                goto rulesimpleIdtfEx;

            }

            switch (alt9)
            {
        	case 1:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:431:6: a= NAME
        	    {
        	        {
        	            BTS(a) 
        	        }


        	        a = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_simpleIdtf2266);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesimpleIdtfEx;
        	        }


        	        {
        	              ATS(a,setName)  
        	        }


        	    }
        	    break;
        	case 2:
        	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:432:6: b= URL
        	    {
        	        {
        	            BTS(b) 
        	        }


        	        b = (pANTLR3_COMMON_TOKEN) MATCHT(URL, &FOLLOW_URL_in_simpleIdtf2282);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesimpleIdtfEx;
        	        }


        	        {
        	              ATS(b,setUrl)   
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulesimpleIdtfEx; /* Prevent compiler warnings */
    rulesimpleIdtfEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end simpleIdtf */

/**
 * $ANTLR start idtfWithInt
 * D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:437:1: idtfWithInt :a= idtf (b= internal )? ;
 */
static void
idtfWithInt(pSCsCParser ctx)
{
    /* Initialize rule variables
     */


    	  //retPtr = new IdentifierWithInternalAST();
    	  INIT_RULE(retPtr);
    	
    {
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:445:7: (a= idtf (b= internal )? )
        // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:446:7: a= idtf (b= internal )?
        {
            {
                BNTS(a)
            }


            FOLLOWPUSH(FOLLOW_idtf_in_idtfWithInt2331);
            idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtfWithIntEx;
            }


            {
                 ANTS(a,setIdentifier)   
            }


            // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:447:5: (b= internal )?
            {
                int alt10=2;
                switch ( LA(1) )
                {
                    case LPAR_INT:
                    	{
                    		alt10=1;
                    	}
                        break;
                }

                switch (alt10)
                {
            	case 1:
            	    // D:\\Programming\\PROJECTS\\Eclipse\\workspace\\ScsGrammar\\src\\SCsC.g:447:7: b= internal
            	    {
            	        {
            	            BNTS(b)
            	        }


            	        FOLLOWPUSH(FOLLOW_internal_in_idtfWithInt2355);
            	        internal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidtfWithIntEx;
            	        }


            	        {
            	             ANTS(b,setInternal)     
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleidtfWithIntEx; /* Prevent compiler warnings */
    ruleidtfWithIntEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {
                     CODE_AFTER_RULE 
                }
            }


    return ;
}
/* $ANTLR end idtfWithInt */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
